apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kadence.fullname" . }}-config
  labels:
    {{- include "kadence.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
