apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kadence.fullname" . }}-secret
  labels:
    {{- include "kadence.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  {{- else if and (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.url }}
  KADENCE_DATABASE_URL: {{ .Values.externalDatabase.url | quote }}
  {{- end }}
